# Generated by Django 5.0.4 on 2024-06-14 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_alter_order_order_date_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='uploads/products'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 6, 14, 12, 10, 5, 889429)),
        ),
    ]
