# Generated by Django 5.0.4 on 2024-06-14 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_category_picture_alter_order_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='picture',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 6, 14, 12, 35, 57, 298100)),
        ),
    ]
