# Generated by Django 5.0.4 on 2024-06-30 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_rename_picture_category_image_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 6, 30, 10, 33, 49, 476833)),
        ),
    ]
