# Generated by Django 5.0.4 on 2024-07-06 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_rename_description_product_description_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_ge',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_ge',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_ge',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 7, 6, 11, 17, 1, 310997)),
        ),
    ]
