# Generated by Django 5.0.4 on 2024-07-27 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_rename_name_ge_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 7, 27, 12, 16, 31, 515458)),
        ),
    ]
