# Generated by Django 5.0.4 on 2024-06-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_delete_my_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
