# Generated by Django 5.0.4 on 2024-06-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_cuponcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuponcode',
            name='sale_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
