# Generated by Django 5.0.4 on 2024-06-30 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_cuponcode_sale_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuponcode',
            name='date',
        ),
        migrations.AddField(
            model_name='cuponcode',
            name='date_creted',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 6, 30, 10, 46, 37, 831353)),
        ),
    ]
