# Generated by Django 5.0.4 on 2024-07-01 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_remove_cuponcode_date_creted_cuponcode_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuponcode',
            name='date_created',
        ),
        migrations.AddField(
            model_name='cuponcode',
            name='date_creted',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='cuponcode',
            name='code',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='cuponcode',
            name='sale_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=150000),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='fullname',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='per_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='size',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='add_information',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='fullname',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='per_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(max_length=200),
        ),
    ]
