# Generated by Django 5.0.4 on 2024-07-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_remove_cuponcode_date_created_cuponcode_date_creted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cupon_used',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
