# Generated by Django 5.0.4 on 2024-07-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_order_cupon_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cupon_used',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
