# Generated by Django 5.0.4 on 2024-07-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_alter_order_cupon_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cupon_used',
            field=models.CharField(default='Cupon code was not used', max_length=200, null=True),
        ),
    ]
