# Generated by Django 5.0.4 on 2024-07-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_alter_order_cupon_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_methode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
