# Generated by Django 5.0.4 on 2024-07-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_order_payment_methode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='per_id',
        ),
    ]
